modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gulp"
version="${mod_version}"
displayName="Gulp"
description='''
Swallow mobs and villagers, carry them in a stomach, and digest them for loot.
'''

[[dependencies.gulp]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gulp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
