modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gulp"
version="${mod_version}"
displayName="Vore Mod"
logoFile="logo.png"
logoBlur=false
description='''
This Mod adds Vore to your world with progression, perks and capacity to carry mobs wherever you want.
'''

[[dependencies.gulp]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gulp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
